title: Synthetix Cache API Documentation
description: Documentation for the Synthetix Cache API (WIP)
theme: minima

baseurl: "/synthetix-cache-api-docs" 
url: "https://collideinscope.github.io" 

# Markdown processing options
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  toc_levels: 1..6

plugins:
  - jekyll-remote-theme

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
