title: Synthetix Cache API Documentation
description: Documentation for the Synthetix Cache API (WIP)

baseurl: "/synthetix-cache-api-docs" 
url: "https://Collideinscope.github.io" 

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  toc_levels: 1..6

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

include:
  - docs/styles.css
